# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f15be85044d968c248462d49549457c4f31ff4e60848e91f2830307f6bffe6f4f39ac5ef7fe9b2573cb78026268e1480a3305dc29afe35e9221e64c8e6001917

test:
  secret_key_base: 1d1f4e8534d7436222ecba4b8147ed443ff711f4f2e80a102da5ffe0d574bfd2801418d05f7810be7d37d1fc1c587fedb35804561abae928007821e0e326d19a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
